const recipes = [
  {
    name: "Muamba de Galinha (Angolan Chicken Stew)",
    ingredients: [
      "1 whole chicken, cut into pieces",
      "2 tablespoons red palm oil",
      "1 large onion, finely chopped",
      "3 cloves of garlic, minced",
      "2 ripe tomatoes, diced",
      "1 red bell pepper, chopped",
      "1 green bell pepper, chopped",
      "1 cup okra, sliced (optional)",
      "2 tablespoons tomato paste",
      "1-2 teaspoons peri-peri sauce or hot sauce (adjust to taste)",
      "1 teaspoon ground ginger",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1 teaspoon smoked paprika",
      "Salt and pepper to taste",
      "2 bay leaves",
      "2 cups chicken broth",
      "Fresh cilantro or parsley for garnish",
    ],
    instructions: [
      "Marinate the Chicken:",
      "1. In a large bowl, season the chicken pieces with salt, pepper, ground ginger, ground cumin, ground coriander, and smoked paprika. Let it marinate for at least 30 minutes.",
      "",
      "Prepare the Vegetables:",
      "2. In a large pot, heat the red palm oil over medium heat. Add the chopped onions and sauté until they are soft and golden.",
      "",
      "Add Aromatics:",
      "3. Add the minced garlic and sauté for an additional minute until fragrant.",
      "",
      "Cook the Chicken:",
      "4. Add the marinated chicken pieces to the pot and brown them on all sides.",
      "",
      "Add Vegetables:",
      "5. Stir in the diced tomatoes, chopped red and green bell peppers, and sliced okra (if using). Cook for a few minutes until the vegetables are slightly softened.",
      "",
      "Spice it Up:",
      "6. Add the tomato paste, peri-peri sauce or hot sauce, and bay leaves. Mix well to coat the chicken and vegetables with the spices.",
      "",
      "Pour in Chicken Broth:",
      "7. Pour in the chicken broth, bring the mixture to a boil, then reduce the heat to low. Cover the pot and let it simmer for about 30-40 minutes, or until the chicken is cooked through and tender.",
      "",
      "Adjust Seasoning:",
      "8. Taste and adjust the seasoning with salt, pepper, and additional spices if needed.",
      "",
      "Serve:",
      "9. Remove the bay leaves. Serve the Muamba de Galinha hot over rice or with a side of funge (a traditional Angolan staple made from cassava).",
      "",
      "Garnish:",
      "10. Garnish with fresh cilantro or parsley before serving.",
      "",
      "Enjoy your delicious Angolan Muamba de Galinha!",
    ],
  },
  // You can add more recipes here...
];

// Access other recipes using recipes[1], recipes[2], etc.
