const recipes = [
  {
    id: 1,
    name: "Muamba de Galinha",
    img: "https://example.com/muamba-de-galinha-image.jpg",
    timeToPrepare: "2 hours",
    ingredients: [
      "1 whole chicken, cut into pieces",
      "2 tablespoons red palm oil",
      "1 large onion, finely chopped",
      "3 cloves of garlic, minced",
      "2 ripe tomatoes, diced",
      "1 red bell pepper, chopped",
      "1 green bell pepper, chopped",
      "1 cup okra, sliced (optional)",
      "2 tablespoons tomato paste",
      "1-2 teaspoons peri-peri sauce or hot sauce (adjust to taste)",
      "1 teaspoon ground ginger",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1 teaspoon smoked paprika",
      "Salt and pepper to taste",
      "2 bay leaves",
      "2 cups chicken broth",
      "Fresh cilantro or parsley for garnish",
    ],
    listOfSteps: [
      "Marinate the Chicken:",
      "1. In a large bowl, season the chicken pieces with salt, pepper, ground ginger, ground cumin, ground coriander, and smoked paprika. Let it marinate for at least 30 minutes.",
      "Prepare the Vegetables:",
      "2. In a large pot, heat the red palm oil over medium heat. Add the chopped onions and sauté until they are soft and golden.",
      "Add Aromatics:",
      "3. Add the minced garlic and sauté for an additional minute until fragrant.",
      "Cook the Chicken:",
      "4. Add the marinated chicken pieces to the pot and brown them on all sides.",
      "Add Vegetables:",
      "5. Stir in the diced tomatoes, chopped red and green bell peppers, and sliced okra (if using). Cook for a few minutes until the vegetables are slightly softened.",
      "Spice it Up:",
      "6. Add the tomato paste, peri-peri sauce or hot sauce, and bay leaves. Mix well to coat the chicken and vegetables with the spices.",
      "Pour in Chicken Broth:",
      "7. Pour in the chicken broth, bring the mixture to a boil, then reduce the heat to low. Cover the pot and let it simmer for about 30-40 minutes, or until the chicken is cooked through and tender.",
      "Adjust Seasoning:",
      "8. Taste and adjust the seasoning with salt, pepper, and additional spices if needed.",
      "Serve:",
      "9. Remove the bay leaves. Serve the Muamba de Galinha hot over rice or with a side of funge (a traditional Angolan staple made from cassava).",
      "Garnish:",
      "10. Garnish with fresh cilantro or parsley before serving.",
      "Enjoy your delicious Angolan Muamba de Galinha!",
    ],
    cuisine: "Angolan",
    favorite: true,
  },
  {
    id: 2,
    name: "Pasteis de Nata",
    img: "https://example.com/pasteis-de-nata-image.jpg",
    timeToPrepare: "1.5 hours",
    ingredients: [
      "2 sheets of puff pastry (store-bought or homemade)",
      "Flour (for dusting)",
      "2 cups whole milk",
      "1 cinnamon stick",
      "1 lemon peel (wide strips)",
      "1 cup granulated sugar",
      "4 tablespoons all-purpose flour",
      "4 tablespoons cornstarch",
      "6 large egg yolks",
      "1 teaspoon vanilla extract",
      "Powdered sugar (for dusting)",
      "Ground cinnamon (for dusting)",
    ],
    listOfSteps: [
      "Prepare the Pastry:",
      "1. If using store-bought puff pastry, roll it out on a floured surface to about 1/8 inch thickness.",
      "2. Cut the pastry into squares that will fit into the cups of a muffin tin.",
      "3. Line each cup of the muffin tin with the pastry, pressing it into the bottom and up the sides. Ensure there is some overhang.",
      "Prepare the Custard Filling:",
      "4. In a saucepan, heat the milk, cinnamon stick, and lemon peel over medium heat until it begins to simmer. Remove from heat and let it cool slightly.",
      "5. In a separate bowl, whisk together sugar, flour, and cornstarch.",
      "6. Gradually whisk the dry ingredients into the warm milk until well combined.",
      "7. Return the mixture to the heat and cook, stirring continuously until it thickens.",
      "8. In a separate bowl, beat the egg yolks. Gradually add a small amount of the hot milk mixture to the eggs, stirring constantly to temper the eggs.",
      "9. Pour the egg mixture back into the saucepan with the milk, whisking continuously.",
      "10. Continue cooking and stirring until the custard is thick and smooth. Remove from heat and stir in the vanilla extract.",
      "Assemble and Bake:",
      "11. Preheat your oven to 475°F (245°C).",
      "12. Fill each pastry-lined cup with the custard mixture, leaving a small space at the top.",
      "13. Bake in the preheated oven for about 12-15 minutes or until the pastry is golden and the custard is lightly browned on top.",
      "14. Remove from the oven and let the custard tarts cool in the tin for a few minutes.",
      "Serve:",
      "15. Carefully remove the custard tarts from the muffin tin and place them on a wire rack to cool completely.",
      "16. Dust with powdered sugar and ground cinnamon before serving.",
      "17. Enjoy your delicious Pasteis de Nata!",
    ],
    cuisine: "Portuguese",
    favorite: true,
  },
  {
    id: 3,
    name: "Msemen",
    img: "https://ohmyfoodness.nl/wp-content/uploads/2020/07/msemmen-2.jpg",
    timeToPrepare: "2 hours",
    ingredients: [
      "4 cups all-purpose flour",
      "1 cup fine semolina",
      "1 teaspoon salt",
      "1 tablespoon sugar",
      "1 tablespoon active dry yeast",
      "1 1/2 to 2 cups warm water",
      "1/4 cup vegetable oil",
      "Butter or vegetable oil (for brushing)",
    ],
    listOfSteps: [
      "In a large bowl, mix the flour, semolina, salt, sugar, and yeast.",
      "Gradually add warm water and knead until you get a soft and elastic dough. You may need more or less water, so add gradually.",
      "Once the dough is well-kneaded, cover it and let it rest for about 10-15 minutes.",
      "Divide the dough into small balls (about the size of a golf ball).",
      "Take each ball, dip it in vegetable oil, and flatten it into a thin rectangle on an oiled surface.",
      "Fold the sides of the rectangle towards the center to create a square shape. Brush with more oil if needed.",
      "Repeat the process with the remaining balls, and let the msemen rest for about 30 minutes, covered.",
      "Heat a griddle or non-stick pan over medium heat. Cook each msemen square on both sides until golden brown and cooked through.",
      "Brush each cooked msemen with butter or oil for added flavor.",
      "Serve warm and enjoy your delicious Msemen!",
    ],
    cuisine: "Moroccan",
    favorite: true,
  },
  {
    id: 4,
    name: "Meatball Burrito",
    img: "https://example.com/meatball-burrito-image.jpg",
    timeToPrepare: "30 minutes",
    ingredients: [
      "1 pound ground beef",
      "1/2 cup breadcrumbs",
      "1/4 cup grated Parmesan cheese",
      "1 egg, beaten",
      "1 teaspoon garlic powder",
      "1 teaspoon onion powder",
      "Salt and pepper to taste",
      "1 cup cooked rice",
      "1 cup black beans, drained and rinsed",
      "1 cup shredded cheese (cheddar or Mexican blend)",
      "Flour tortillas",
      "Salsa, guacamole, sour cream (optional, for serving)",
    ],
    listOfSteps: [
      "Preheat your oven to 375°F (190°C).",
      "In a large bowl, combine ground beef, breadcrumbs, Parmesan cheese, beaten egg, garlic powder, onion powder, salt, and pepper. Mix until well combined.",
      "Shape the mixture into meatballs and place them on a baking sheet lined with parchment paper.",
      "Bake the meatballs in the preheated oven for about 20 minutes or until cooked through and browned on the outside.",
      "In a large skillet, heat cooked rice and black beans over medium heat until warmed through.",
      "Warm the flour tortillas in a dry skillet or microwave according to the package instructions.",
      "Assemble the burritos by placing a spoonful of rice and black beans on each tortilla. Add meatballs and sprinkle with shredded cheese.",
      "Fold the sides of the tortilla over the filling and roll it into a burrito.",
      "Optional: Serve with salsa, guacamole, and sour cream on the side.",
      "Enjoy your delicious Meatball Burrito!",
    ],
    cuisine: "Mexican",
    favorite: true,
  },
];

module.exports = recipes;
