const recipes = [
  {
    id: 1,
    name: "Muamba de Galinha (Angolan Chicken Stew)",
    ingredients: [
      "1 whole chicken, cut into pieces",
      "2 tablespoons red palm oil",
      "1 large onion, finely chopped",
      "3 cloves of garlic, minced",
      "2 ripe tomatoes, diced",
      "1 red bell pepper, chopped",
      "1 green bell pepper, chopped",
      "1 cup okra, sliced (optional)",
      "2 tablespoons tomato paste",
      "1-2 teaspoons peri-peri sauce or hot sauce (adjust to taste)",
      "1 teaspoon ground ginger",
      "1 teaspoon ground cumin",
      "1 teaspoon ground coriander",
      "1 teaspoon smoked paprika",
      "Salt and pepper to taste",
      "2 bay leaves",
      "2 cups chicken broth",
      "Fresh cilantro or parsley for garnish",
    ],
    instructions: [
      "Marinate the Chicken:",
      "1. In a large bowl, season the chicken pieces with salt, pepper, ground ginger, ground cumin, ground coriander, and smoked paprika. Let it marinate for at least 30 minutes.",
      "",
      "Prepare the Vegetables:",
      "2. In a large pot, heat the red palm oil over medium heat. Add the chopped onions and sauté until they are soft and golden.",
      "",
      "Add Aromatics:",
      "3. Add the minced garlic and sauté for an additional minute until fragrant.",
      "",
      "Cook the Chicken:",
      "4. Add the marinated chicken pieces to the pot and brown them on all sides.",
      "",
      "Add Vegetables:",
      "5. Stir in the diced tomatoes, chopped red and green bell peppers, and sliced okra (if using). Cook for a few minutes until the vegetables are slightly softened.",
      "",
      "Spice it Up:",
      "6. Add the tomato paste, peri-peri sauce or hot sauce, and bay leaves. Mix well to coat the chicken and vegetables with the spices.",
      "",
      "Pour in Chicken Broth:",
      "7. Pour in the chicken broth, bring the mixture to a boil, then reduce the heat to low. Cover the pot and let it simmer for about 30-40 minutes, or until the chicken is cooked through and tender.",
      "",
      "Adjust Seasoning:",
      "8. Taste and adjust the seasoning with salt, pepper, and additional spices if needed.",
      "",
      "Serve:",
      "9. Remove the bay leaves. Serve the Muamba de Galinha hot over rice or with a side of funge (a traditional Angolan staple made from cassava).",
      "",
      "Garnish:",
      "10. Garnish with fresh cilantro or parsley before serving.",
      "",
      "Enjoy your delicious Angolan Muamba de Galinha!",
    ],
  },
  {
    id: 2,
    name: "Pasteis de Nata",
    ingredients: [
      "2 sheets of puff pastry (store-bought or homemade)",
      "Flour (for dusting)",
      "2 cups whole milk",
      "1 cinnamon stick",
      "1 lemon peel (wide strips)",
      "1 cup granulated sugar",
      "4 tablespoons all-purpose flour",
      "4 tablespoons cornstarch",
      "6 large egg yolks",
      "1 teaspoon vanilla extract",
      "Powdered sugar (for dusting)",
      "Ground cinnamon (for dusting)",
    ],
    instructions: [
      "Prepare the Pastry:",
      "1. If using store-bought puff pastry, roll it out on a floured surface to about 1/8 inch thickness.",
      "2. Cut the pastry into squares that will fit into the cups of a muffin tin.",
      "3. Line each cup of the muffin tin with the pastry, pressing it into the bottom and up the sides. Ensure there is some overhang.",
      "",
      "Prepare the Custard Filling:",
      "1. In a saucepan, heat the milk, cinnamon stick, and lemon peel over medium heat until it begins to simmer. Remove from heat and let it cool slightly.",
      "2. In a separate bowl, whisk together sugar, flour, and cornstarch.",
      "3. Gradually whisk the dry ingredients into the warm milk until well combined.",
      "4. Return the mixture to the heat and cook, stirring continuously until it thickens.",
      "5. In a separate bowl, beat the egg yolks. Gradually add a small amount of the hot milk mixture to the eggs, stirring constantly to temper the eggs.",
      "6. Pour the egg mixture back into the saucepan with the milk, whisking continuously.",
      "7. Continue cooking and stirring until the custard is thick and smooth. Remove from heat and stir in the vanilla extract.",
      "",
      "Assemble and Bake:",
      "1. Preheat your oven to 475°F (245°C).",
      "2. Fill each pastry-lined cup with the custard mixture, leaving a small space at the top.",
      "3. Bake in the preheated oven for about 12-15 minutes or until the pastry is golden and the custard is lightly browned on top.",
      "4. Remove from the oven and let the custard tarts cool in the tin for a few minutes.",
      "",
      "Serve:",
      "1. Carefully remove the custard tarts from the muffin tin and place them on a wire rack to cool completely.",
      "2. Dust with powdered sugar and ground cinnamon before serving.",
      "3. Enjoy your delicious Pasteis de Nata!",
    ],
  },
  // You can add more recipes here...
];

// Access other recipes using recipes[1], recipes[2], etc.
module.exports = recipes;
